# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy_dev:
    machine: true
    steps:
      - checkout
      - run: touch .env
      - run: make create_account_file
      - run: make prepare_volume
      - run: make pdf
      - run: make client_install
      - run: make client_build
      - run: make gcloud_login
      - run: make init
      - run: make plan
      - run: make apply
      - run: make client_upload
    environment:
      TF_VAR_ENV: "dev"
      TF_VAR_DOMAIN: "dev.burlinski.info"

  deploy_prod:
    machine: true
    steps:
      - checkout
      - run: touch .env
      - run: make create_account_file
      - run: make prepare_volume
      - run: make pdf
      - run: make client_install
      - run: make client_build
      - run: make gcloud_login
      - run: make init
      - run: make plan
      - run: make apply
      - run: make client_upload
    environment:
      TF_VAR_ENV: "prod"
      TF_VAR_DOMAIN: "burlinski.info"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy_dev
      - deploy_prod:
          requires:
            - deploy_dev
only: sequential-branch-filter